---
- import_playbook: ../init/main.yml
  vars:
    skip_verison: True
    l_upgrade_non_node_hosts: "oo_masters_to_config:oo_etcd_to_config:oo_lb_to_config"

- import_playbook: private/upgrade_main.yml
